[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''
if flags.cards_to_draw then context.amount = flags.cards_to_draw end
'''
position = "after"
payload = '''
if flags.dollar_override then context.stlr_dollar_amount = flags.dollar_override end
'''
match_indent = true
times = 1